config/routes.rb
Liannardo::Application.routes.draw do
  get "members/index"

  get "members/show"

  get "members/edit"

  get "members/update"

  devise_for :users, controllers: {registrations: :registrations, omniauth_callbacks: "omniauth_callbacks"}

  resources :users, only: [:index]
  
  devise_scope :user do
    get "/login", to: "devise/sessions#new"
  end
  resources :votes

  resources :posts
  resources :members

  get 'apicalls/facebook_auth', to:  'apicalls#facebook_auth', as: 'facebook_auth'

  root :to => 'posts#index'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :sentiment, :user_id, :post_id

  belongs_to :user
  belongs_to :post
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.json
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(params[:vote])
    @vote.user_id = current_user.id
    vote_exist = Vote.all.select do |vote|
      if vote.user_id == @vote.user_id
        if vote.post_id == @vote.post_id
          if vote.sentiment == @vote.sentiment
          vote
          end
        end  
      end  
    end 
    if vote_exist.length >0
      Vote.destroy(vote_exist.first.id)
    else
      @vote.save
    end
    respond_to do |format|
      format.html { redirect_to @votes}
      format.json { render json: @votes}
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sentiment %><br />
    <%= f.check_box :sentiment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<div>
  <div>
    <div>Sentiment</div>
    <div></div>
    <div></div>
    <div></div>
  </div>

<% @votes.each do |vote| %>
  <div>
    <div><%= vote.sentiment %></div>
    <div><%= link_to 'Show', vote %></div>
    <div><%= link_to 'Edit', edit_vote_path(vote) %></div>
    <div><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></div>
  </div>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sentiment:</b>
  <%= @vote.sentiment %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>