config/routes.rb
Liannardo::Application.routes.draw do
  get "members/index"

  get "members/show"

  get "members/edit"

  get "members/update"

  devise_for :users, controllers: {registrations: :registrations, omniauth_callbacks: "omniauth_callbacks"}

  resources :users, only: [:index]
  
  devise_scope :user do
    get "/login", to: "devise/sessions#new"
  end
  resources :votes

  resources :posts
  resources :members

  get 'apicalls/facebook_auth', to:  'apicalls#facebook_auth', as: 'facebook_auth'

  root :to => 'posts#index'

end

app/views/layouts/_classic_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/login/">Welcome to LIANNARDO!</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          
          <ul class="nav navbar-nav">

            <li class="active"><%= link_to 'sign in', new_user_session_path %></li>
            <li><%= link_to 'sign up', new_user_registration_path %></li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login with:<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          
            <li><%= link_to "Google", user_omniauth_authorize_path(:google_oauth2)%></li>
            <li><%= link_to "Facebook", user_omniauth_authorize_path(:facebook)%></li>
            <li><%= link_to "Linkedin", user_omniauth_authorize_path(:linkedin)%></li>
            <li><%= link_to "Twitter", user_omniauth_authorize_path(:twitter)%></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">          
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/about">About Us</a></li>
            <li><a href="/terms">Terms & Conditions</a></li>
          </ul>

          </ul>
        </li>
      </ul>


      <!-- <form class="navbar-form navbar-left" role="search"> -->
        <!-- <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div> -->
        <!-- <button type="submit" class="btn btn-default">Submit</button> -->
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_user_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/members/<%=current_user.id%>"><%= current_user.name %></a>
    </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= active_menu "View Feed", posts_path %>
        <%= active_menu "View Members", members_path %>
        <li><a href="#myModal" data-toggle="modal" data-target="#myModal">New Post</a></li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li>
          <img id="nav_image" src="<%= getImage(current_user) %>" />
        </li>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/about">About Us</a></li>
            <li><a href="/terms">Terms & Conditions</a></li>
            <li class="divider"></li>
            <li><%= link_to 'Edit User', edit_user_registration_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">New Post</h4>
      </div>
      <div class="modal-body">
        <form onsubmit="return false;">
            <input type="textfield" size = 41 maxlength = 41, />
            <a class="btn btn-primary" onclick="this.parentNode.submit();" href="">Create Post</a>
        </form>
      </div>
 <!--        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary"><div class="actions">Submit</div></button>
        </div> -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='http://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
  <title>CheerUps</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="main_background">
  <% if current_user %>
    <%= render "layouts/user_menu"%>
  <% else %>
    <%= render "layouts/classic_menu"%>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>





</body>
</html>