config/routes.rb
Liannardo::Application.routes.draw do
  get "members/index"

  get "members/show"

  get "members/edit"

  get "members/update"

  devise_for :users, controllers: {registrations: :registrations, omniauth_callbacks: "omniauth_callbacks"}

  resources :users, only: [:index]
  
  devise_scope :user do
    get "/login", to: "devise/sessions#new"
  end
  resources :votes

  resources :posts
  resources :members

  get 'apicalls/facebook_auth', to:  'apicalls#facebook_auth', as: 'facebook_auth'

  root :to => 'posts#index'

end

app/models/member.rb
class Member < User

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @q = Member.search(params[:q])
    if params[:q]
        # raise
    end
    @users = @q.result(distinct: true)
    # @users = Member.all
    # @p = User.search(params[:p])
    # @users = @p.result(distinct: true)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    @following = @user.users.include? current_user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def edit

    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:user][:user_id])
    #subscribing to user
    if params[:user][:follow] == 'false'
      @user.users << current_user
    else params[:user][:follow] == 'true'
      @user.users.delete(current_user)
    end

    respond_to do |format|
      
      format.json { render :json => "success" }

    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
  def currentUserVotes(post)
    votes = post.votes.select do |vote|
      if vote.user_id == current_user.id
        vote
      end
    end
    binding.pry
    vote
  end


end

app/views/members/_feed.html.erb
<div class="profile_feed">

  <table class="list_own_posts">
  <tr>
    
    <th></th>
    <th></th>
    <th><span class="glyphicon glyphicon-thumbs-up"></span></th>
    <th><span class="glyphicon glyphicon-thumbs-down"></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>

  </tr>


    <% @user.posts.each do |post_record| %>
      

      <!-- MOVE TO HELPER -->
      <% if post_record.repost_id %>
        <% post = Post.find(post_record.repost_id)%>
      <% else %>
        <% post = Post.find(post_record.id)%>
      <% end %>
      <!-- MOVE TO HELPER -->

      
      <!-- MOVE TO HELPER -->
      <% likes = post.votes.all.map do |vote| %>
        <% vote.sentiment if vote.sentiment == true %>
      <% end %>
      <% likes.delete(nil)%>
      <% hates = post.votes.all.map do |vote| %>
        <% vote.sentiment if vote.sentiment == false %>
      <% end %>
      <% hates.delete(nil)%>
      <!-- MOVE TO HELPER -->



        <div><%= post.content %></div>
        
        <% if post_record.repost_id %>
          <div>(RT)<%= link_to post.user.name, member_path(post.user) %></div>
        <% else %>

          <div><%= link_to @user.name, member_path(@user) %></div>

        <% end %>
        <div class="likes"><%= likes.length %></div>
        <div class="hates"><%= hates.length %></div>
        <div class="id" style="visibility:hidden;"><%= post.id %></div>



        <!-- MOVE ALL OF THIS METHOD TO HELPERS -->
        <!-- Getting votes made by current user on this post -->
        <%vote = post.votes.select do |vote| %>
          <% if vote.user_id == current_user.id %>  
          <% vote %>
          <% end %>
        <% end %>
        <!-- Checking if one vote or two made and what type of vote if only one made. Adding classes depending on votes already made -->
        <% if vote.length ==1 %>
          <% sentiment = vote.first.sentiment %>
          <% if sentiment == true %>
            <% starting_liked_status = "liked_status"%>
            <% starting_hated_status = "unchecked_status"%>
          <% else sentiment == false %>
          <% starting_liked_status = "unchecked_status"%>
          <% starting_hated_status = "hated_status"%>
          <% end %>
        <% elsif vote.length ==2%>
          <% starting_liked_status = "liked_status"%>
          <% starting_hated_status = "hated_status"%>
        <% else %>
          <% starting_liked_status = "unchecked_status"%>
          <% starting_hated_status = "unchecked_status"%>
        <% end %>
        <div><button class = "<%= starting_liked_status %> like"><span class="glyphicon glyphicon-thumbs-up"></span></button></div>
        <div><button class = "<%= starting_hated_status %> hate"><span class="glyphicon glyphicon-thumbs-down"></span></button></div>

        <div><%= link_to 'Show', post %></div>
        <div><%= link_to 'Edit', edit_post_path(post) %></div>
        <div><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </tr>    
    <% end %>
  </table>


</div>

app/views/members/_membersfeed.html.erb
<div class="profile_feed">
  <% @user.posts.each do |post_record| %>
    <div class="profile_post">  
      <% if post_record.repost_id %>
        <% post = Post.find(post_record.repost_id)%>
      <% else %>
        <% post = Post.find(post_record.id)%>
      <% end %>

      <div class="post_first_col">
        <% if post_record.repost_id %>
          <div id="user_profile_name">(RT)<%= link_to post.user.name, member_path(post.user) %>
          </div>
        <% else %>
          <div id="user_profile_name"><%= link_to @user.name, member_path(@user) %>
          </div>  
        <% end %>
        
      </div>
      <div class="post_second_col">
        <div class="feed_content_div"><%= post.content %>
        </div>
        
        <% votes = currentUserVotes(post)%>

        <!-- Checking if one vote or two made and what type of vote if only one made. Adding classes depending on votes already made -->
        <!-- MOVE TO HELPER -->
        <% if votes.length ==1 %>
          <% sentiment = votes.first.sentiment %>
          <% if sentiment == true %>
            <% starting_liked_status = "liked_status"%>
            <% starting_hated_status = "unchecked_status"%>
          <% else sentiment == false %>
          <% starting_liked_status = "unchecked_status"%>
          <% starting_hated_status = "hated_status"%>
          <% end %>
        <% elsif votes.length ==2%>
          <% starting_liked_status = "liked_status"%>
          <% starting_hated_status = "hated_status"%>
        <% else %>
          <% starting_liked_status = "unchecked_status"%>
          <% starting_hated_status = "unchecked_status"%>
        <% end %>

        <!-- MOVE TO HELPER -->
        <div class="feed_like_div">
          <button id="feed_like_button" class = "<%= starting_liked_status %> like"><span class="glyphicon glyphicon-thumbs-up"></span></button>
        </div>
        <div class="likes"><%= numberOfLikes(post) %>
        </div>
        <div class="feed_hate_div">
          <button id="feed_hate_button" class = "<%= starting_hated_status %> hate"><span class="glyphicon glyphicon-thumbs-down"></span></button></button>
        </div>
        <div class="hates"><%= numberOfHates(post) %></div>
        <div class="id" style="visibility:hidden;">
          <%= post.id %>
        </div></div>




        
    </div>    
  <% end %>
</div>

app/views/members/_sidebar.html.erb
<div class="profile_sidebar">
  <h1><%= @user.name %>'s Profile</h1>
  <div class="left-side">
  <img id="prof_pic" src="<%= getImage(@user) %>" />
  </div>

  <br/>
  <% if @user.id == current_user.id %>
  <% else %>
    <% if @following %>
      <button class="follow following">Following</button>
    <% else %>
      <button class="follow not_following">Follow</button>
    <% end %>
  <% end %>
    
  <div class="following_user" style="display: none;"><%= @user.id %></div>
  <div class="current_user"><% current_user.id %></div>
  <b>Followers:</b><div class="follower_count"><%= @user.users.length %></div>
  <p>
    <% @user.name %>
  </p>
  <p>
    <% if @user.bio ==nil %>
       
    <% else %>
      <b>About Me:</b>
      <%= @user.bio %>
    <%end %>
  </p>

  <% if @user.users.length == 0 %>

    <% else %>
      <div class="followers"><b>Followers:</b>
       <% @user.users.each do |user| %>
        <%= user.name %>
       <% end %>
       </div>
  <% end %>




  <b>Following:</b>
   <% User.all.each do |user| %>
    <% if user.users.include? @user %>
      <%= user.name %>
    <% else %>
        
    <% end %>
  <% end %>

  <br>
     

  <% following = User.all.select do |user| %>
    <% is_following = user.users.select do |following| %>
      <% if following.id == current_user.id %>
        <% following %>
      <% end %>
    <% end %>
    <% if is_following.length > 0 %>
    <% user %>
    <% end %>
  <% end %>
  <% current_user_and_following = following << current_user %>


</div>

app/views/members/index.html.erb
<h1>All users</h1>


<div id="user_search_box">
  <b>Search for users:</b><%= search_form_for @q do |f| %>
      <%= f.text_field :name_cont %>
      <%= f.submit %>

  <% end %>

  
</div>

<% @users.each do |user| %>
  <div class="member_listing">
    <div class="member_listing_name"><%= link_to user.name, user %></div>
    <% if user.profile_picture==nil %>
      <div class="memlistimage_div"><img class="member_listing_image" src="<%= user.image %>" /></div>
    <% else %>
      <div class="memlistimage_div"><img class="member_listing_image" src="<%= user.profile_picture %>" /></div>
    <% end%>
    <div class="member_listing_bio"><%= user.bio %></div> 
   </div>
<% end %>

app/views/members/show.html.erb
<%= render "members/sidebar"%>

<%= render "members/membersfeed"%>
<p id="notice"><%= notice %></p>



<br />